name: CICD
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t krishnayadav21/react-app-test .
 
      - name: Publish image to Docker Hub
        run: docker push krishnayadav21/react-app-test:latest
 
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull krishnayadav21/react-app-test:latest
 
      - name: Delete Old Container
        run: docker rm -f reactContainer
 
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer krishnayadav21/react-app-test